customhost = "employee.cvfzhzwthqsa.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chooyuanchee-employee"
customregion = "us-east-1b"
